name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
