name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Zip artifact for deployment
      run: zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app 

      - name: unzip artifact for deployment
        run: unzip release.zip

      - name: Delete Release Zip File
        run: rm release.zip

      - name: Copy To Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          source: "."
          target: C:\Users\niraj\${{ github.run_id }}

      - name: Make Dir For Current Deplyment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          script: |
            mkdir C:\Users\niraj\${{ github.run_number }}.${{ github.run_attempt }}
            
          
      - name: Backup From Live
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          script: | 
            xcopyC:\Users\niraj\live\. C:\Users\niraj\${{ github.run_number }}.${{ github.run_attempt }}\ /E /C /H /R /K /O /Y
      - name: Remove all files
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          script: | 
            C:\Users\niraj\delete.bat
      - name: Deploy To Live
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          script: | 
            xcopy C:\Users\niraj\${{ github.run_id }}\. C:\Users\niraj\live\ /E /C /H /R /K /O /Y
      - name: Copy Configurations
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          script: | 
            xcopy C:\Users\niraj\web.config C:\Users\niraj\live\ /E /C /H /R /K /O /Y
      - name: Remove Dir
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          script: | 
            rmdir /s /q C:\Users\niraj\${{ github.run_id }}
      - name: Restart IIS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WINDOWS_SERVER_ADDRESS }}
          username: ${{ secrets.WINDOWS_SERVER_USERNAME }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          script: |
            iisreset
