name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: windows-latest
  

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build

      #- name: Install IIS Web Deployment Tool
      #uses: microsoft/iis-web-deploy@v1

      - name: Deploy to IIS
        run: msdeploy -verb:sync -source:artifact -dest:auto,computerName="13.48.137.69",username="Administrator",password="cyOV@lnZc@Jh-;u1bV8aJ.c8lIdBYhNp",authtype="Basic",includeAcls="False",dirPath="build" -enableRule:DoNotDeleteRule

