name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build
    
    - name: Copy files to server
      run: |
        $secpasswd = ConvertTo-SecureString "cyOV@lnZc@Jh-;u1bV8aJ.c8lIdBYhNp" -AsPlainText -Force
        $mycreds = New-Object System.Management.Automation.PSCredential ("Administrator", $secpasswd)
        Copy-Item -Path "build/*" -Destination "\\13.48.137.69\C$\inetpub\wwwroot\my-react-app" -Recurse -Force -Credential $mycreds

    - name: Restart IIS
      run: |
        Restart-Service -Name 'W3SVC' -Force
