name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Archive Build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    runs-on: window-server
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: Unzip artifact for deployment on Windows
      run: Expand-Archive -Path release.zip -DestinationPath . -Force

    - name: Copy artifact to Windows Server
      run: |
        $serverAddress = "13.48.137.69"
        $username = "Administrator"
        $password = "cyOV@lnZc@Jh-;u1bV8aJ.c8lIdBYhNp"
        $destination = "\\$serverAddress\C$\Users\niraj"
        try {
            New-PSDrive -Name Z -PSProvider FileSystem -Root $destination -Credential (New-Object PSCredential $username, (ConvertTo-SecureString $password -AsPlainText -Force)) -ErrorAction Stop
            Copy-Item -Path .\* -Destination "Z:\" -Recurse -Force
        } catch {
            Write-Host "Error: $_"
            Write-Host "Destination Path: $destination"
            Write-Host "Server Address: $serverAddress"
        } finally {
            Remove-PSDrive -Name Z -ErrorAction SilentlyContinue
        }



