name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build
    
    - name: Map network drive
      run: |
        $secpasswd = ConvertTo-SecureString "cyOV@lnZc@Jh-;u1bV8aJ.c8lIdBYhNp" -AsPlainText -Force
        $mycreds = New-Object System.Management.Automation.PSCredential ("Administrator", $secpasswd)

    - name: Create destination directory if it doesn't exist
      run: |
        if (-not (Test-Path "C:\inetpub\wwwroot\react")) {
          New-Item -Path "C:\inetpub\wwwroot\react" -ItemType Directory
        }

    - name: Copy files to server
      run: |
        Copy-Item -Path "dist/*" -Destination "C:\inetpub\wwwroot\react" -Recurse -Force

    - name: Unmap network drive
      run: |
        Remove-PSDrive -Name Z

    - name: Restart IIS
      run: |
        Restart-Service -Name 'W3SVC' -Force
