name: Node.js CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use a self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Zip artifact for deployment
        run: Compress-Archive -Path ./* -DestinationPath release.zip -Force

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
  
      - name: Unzip artifact for deployment on Windows
        run: Expand-Archive -Path release.zip -DestinationPath . -Force
  
      - name: Copy artifact to Windows Server
        run: |
          $serverAddress = "13.48.137.69"
          $username = "Administrator"
          $password = "cyOV@lnZc@Jh-;u1bV8aJ.c8lIdBYhNp"
          $destination = "\\$serverAddress\C$\Users\niraj"
          try {
              New-PSDrive -Name Z -PSProvider FileSystem -Root $destination -Credential (New-Object PSCredential $username, (ConvertTo-SecureString $password -AsPlainText -Force)) -ErrorAction Stop
              Copy-Item -Path .\* -Destination "Z:\" -Recurse -Force
          } catch {
              Write-Host "Error: $_"
              Write-Host "Destination Path: $destination"
              Write-Host "Server Address: $serverAddress"
          } finally {
              Remove-PSDrive -Name Z -ErrorAction SilentlyContinue
          }
